# Generated by Django 2.1.7 on 2019-03-23 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('training', models.TextField(blank=True, max_length=500)),
                ('date', models.DateField(default=datetime.date.today)),
                ('grass', models.BooleanField(blank=True, choices=[(True, 'Natural'), (False, 'Artificial')])),
                ('wet', models.BooleanField(blank=True)),
                ('temp', models.IntegerField(blank=True)),
                ('hum', models.IntegerField(blank=True)),
                ('additional_info', models.TextField(blank=True, max_length=240)),
            ],
        ),
    ]
