# Generated by Django 2.1.7 on 2019-03-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('data_consent', models.BooleanField()),
                ('age', models.IntegerField()),
                ('foot_size', models.IntegerField()),
                ('weight', models.IntegerField(help_text='Weight in Kg')),
                ('height', models.IntegerField(help_text='Height in cm')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteVest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vest_num', models.IntegerField()),
                ('time', models.CharField(max_length=8)),
                ('id_athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SensorAthlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=32)),
                ('id_athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Athlete')),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='place',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='athlete',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Session'),
        ),
    ]
