# Generated by Django 2.1.7 on 2019-03-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190323_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='foot_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.PositiveIntegerField(help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.PositiveIntegerField(help_text='Weight in Kg'),
        ),
        migrations.AlterField(
            model_name='session',
            name='grass',
            field=models.IntegerField(blank=True, choices=[(0, 'Natural'), (1, 'Artificial'), (2, 'Street')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='hum',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='temp',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
