# Generated by Django 2.1.7 on 2019-03-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190324_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='grass',
            field=models.IntegerField(choices=[(0, 'Natural'), (1, 'Artificial'), (2, 'Street')], verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hum',
            field=models.PositiveIntegerField(blank=True, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='session',
            name='temp',
            field=models.PositiveIntegerField(blank=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='session',
            name='wet',
            field=models.BooleanField(blank=True, verbose_name='Surface was wet'),
        ),
    ]
